/* eslint-disable */
// Auto-generated by `supabase gen types typescript` (via Supabase MCP). Do not hand-edit —
// regenerate instead when the schema changes.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: '14.5';
  };
  public: {
    Tables: {
      calendar_connections: {
        Row: {
          access_token: string | null;
          access_token_expires_at: string | null;
          calendar_id: string | null;
          calendar_name: string | null;
          created_at: string;
          default_studio_id: string | null;
          google_account_email: string | null;
          id: string;
          last_synced_at: string | null;
          provider: string;
          refresh_token: string;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          access_token?: string | null;
          access_token_expires_at?: string | null;
          calendar_id?: string | null;
          calendar_name?: string | null;
          created_at?: string;
          default_studio_id?: string | null;
          google_account_email?: string | null;
          id?: string;
          last_synced_at?: string | null;
          provider?: string;
          refresh_token: string;
          updated_at?: string;
          user_id: string;
        };
        Update: {
          access_token?: string | null;
          access_token_expires_at?: string | null;
          calendar_id?: string | null;
          calendar_name?: string | null;
          created_at?: string;
          default_studio_id?: string | null;
          google_account_email?: string | null;
          id?: string;
          last_synced_at?: string | null;
          provider?: string;
          refresh_token?: string;
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'calendar_connections_default_studio_id_fkey';
            columns: ['default_studio_id'];
            isOneToOne: false;
            referencedRelation: 'studios';
            referencedColumns: ['id'];
          },
        ];
      };
      events: {
        Row: {
          attendance_count: number | null;
          created_at: string;
          description: string | null;
          end_time: string;
          external_id: string | null;
          ics_feed_id: string | null;
          id: string;
          location: string | null;
          notes: string | null;
          rate_override: number | null;
          source: string;
          start_time: string;
          status: string;
          studio_id: string | null;
          title: string;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          attendance_count?: number | null;
          created_at?: string;
          description?: string | null;
          end_time: string;
          external_id?: string | null;
          ics_feed_id?: string | null;
          id?: string;
          location?: string | null;
          notes?: string | null;
          rate_override?: number | null;
          source: string;
          start_time: string;
          status?: string;
          studio_id?: string | null;
          title: string;
          updated_at?: string;
          user_id: string;
        };
        Update: {
          attendance_count?: number | null;
          created_at?: string;
          description?: string | null;
          end_time?: string;
          external_id?: string | null;
          ics_feed_id?: string | null;
          id?: string;
          location?: string | null;
          notes?: string | null;
          rate_override?: number | null;
          source?: string;
          start_time?: string;
          status?: string;
          studio_id?: string | null;
          title?: string;
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'events_ics_feed_id_fkey';
            columns: ['ics_feed_id'];
            isOneToOne: false;
            referencedRelation: 'ics_feeds';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'events_studio_id_fkey';
            columns: ['studio_id'];
            isOneToOne: false;
            referencedRelation: 'studios';
            referencedColumns: ['id'];
          },
        ];
      };
      ics_feeds: {
        Row: {
          created_at: string;
          default_studio_id: string | null;
          id: string;
          last_synced_at: string | null;
          name: string;
          updated_at: string;
          url: string;
          user_id: string;
        };
        Insert: {
          created_at?: string;
          default_studio_id?: string | null;
          id?: string;
          last_synced_at?: string | null;
          name: string;
          updated_at?: string;
          url: string;
          user_id: string;
        };
        Update: {
          created_at?: string;
          default_studio_id?: string | null;
          id?: string;
          last_synced_at?: string | null;
          name?: string;
          updated_at?: string;
          url?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'ics_feeds_default_studio_id_fkey';
            columns: ['default_studio_id'];
            isOneToOne: false;
            referencedRelation: 'studios';
            referencedColumns: ['id'];
          },
        ];
      };
      import_activity: {
        Row: {
          error_message: string | null;
          finished_at: string | null;
          id: string;
          records_created: number;
          records_processed: number;
          records_skipped: number;
          records_updated: number;
          source: string;
          started_at: string;
          status: string;
          user_id: string;
        };
        Insert: {
          error_message?: string | null;
          finished_at?: string | null;
          id?: string;
          records_created?: number;
          records_processed?: number;
          records_skipped?: number;
          records_updated?: number;
          source: string;
          started_at?: string;
          status?: string;
          user_id: string;
        };
        Update: {
          error_message?: string | null;
          finished_at?: string | null;
          id?: string;
          records_created?: number;
          records_processed?: number;
          records_skipped?: number;
          records_updated?: number;
          source?: string;
          started_at?: string;
          status?: string;
          user_id?: string;
        };
        Relationships: [];
      };
      invoice_line_items: {
        Row: {
          amount: number;
          attendance_count: number | null;
          compensation_type: string;
          created_at: string;
          event_date: string;
          event_id: string | null;
          hours: number;
          id: string;
          invoice_id: string;
          rate: number;
          title: string;
          user_id: string;
        };
        Insert: {
          amount: number;
          attendance_count?: number | null;
          compensation_type: string;
          created_at?: string;
          event_date: string;
          event_id?: string | null;
          hours: number;
          id?: string;
          invoice_id: string;
          rate: number;
          title: string;
          user_id: string;
        };
        Update: {
          amount?: number;
          attendance_count?: number | null;
          compensation_type?: string;
          created_at?: string;
          event_date?: string;
          event_id?: string | null;
          hours?: number;
          id?: string;
          invoice_id?: string;
          rate?: number;
          title?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'invoice_line_items_event_id_fkey';
            columns: ['event_id'];
            isOneToOne: false;
            referencedRelation: 'events';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'invoice_line_items_invoice_id_fkey';
            columns: ['invoice_id'];
            isOneToOne: false;
            referencedRelation: 'invoices';
            referencedColumns: ['id'];
          },
        ];
      };
      invoices: {
        Row: {
          created_at: string;
          due_date: string;
          id: string;
          invoice_number: string | null;
          issue_date: string | null;
          notes: string | null;
          period_end: string;
          period_start: string;
          status: string;
          studio_id: string | null;
          studio_name: string;
          subtotal: number;
          total: number;
          updated_at: string;
          user_id: string;
          vat_amount: number;
          vat_rate: number | null;
        };
        Insert: {
          created_at?: string;
          due_date: string;
          id?: string;
          invoice_number?: string | null;
          issue_date?: string | null;
          notes?: string | null;
          period_end: string;
          period_start: string;
          status?: string;
          studio_id?: string | null;
          studio_name: string;
          subtotal?: number;
          total?: number;
          updated_at?: string;
          user_id: string;
          vat_amount?: number;
          vat_rate?: number | null;
        };
        Update: {
          created_at?: string;
          due_date?: string;
          id?: string;
          invoice_number?: string | null;
          issue_date?: string | null;
          notes?: string | null;
          period_end?: string;
          period_start?: string;
          status?: string;
          studio_id?: string | null;
          studio_name?: string;
          subtotal?: number;
          total?: number;
          updated_at?: string;
          user_id?: string;
          vat_amount?: number;
          vat_rate?: number | null;
        };
        Relationships: [
          {
            foreignKeyName: 'invoices_studio_id_fkey';
            columns: ['studio_id'];
            isOneToOne: false;
            referencedRelation: 'studios';
            referencedColumns: ['id'];
          },
        ];
      };
      studios: {
        Row: {
          address: string | null;
          compensation_type: string;
          compensation_value: number;
          contact_person: string | null;
          created_at: string;
          email: string | null;
          id: string;
          match_keywords: string[];
          metadata: Json;
          name: string;
          notes: string | null;
          phone: string | null;
          reference_id: string | null;
          status: string;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          address?: string | null;
          compensation_type: string;
          compensation_value: number;
          contact_person?: string | null;
          created_at?: string;
          email?: string | null;
          id?: string;
          match_keywords?: string[];
          metadata?: Json;
          name: string;
          notes?: string | null;
          phone?: string | null;
          reference_id?: string | null;
          status?: string;
          updated_at?: string;
          user_id: string;
        };
        Update: {
          address?: string | null;
          compensation_type?: string;
          compensation_value?: number;
          contact_person?: string | null;
          created_at?: string;
          email?: string | null;
          id?: string;
          match_keywords?: string[];
          metadata?: Json;
          name?: string;
          notes?: string | null;
          phone?: string | null;
          reference_id?: string | null;
          status?: string;
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [];
      };
      subscriptions: {
        Row: {
          cancel_at_period_end: boolean;
          created_at: string;
          current_period_end: string | null;
          id: string;
          status: string;
          stripe_customer_id: string;
          stripe_subscription_id: string | null;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          cancel_at_period_end?: boolean;
          created_at?: string;
          current_period_end?: string | null;
          id?: string;
          status?: string;
          stripe_customer_id: string;
          stripe_subscription_id?: string | null;
          updated_at?: string;
          user_id: string;
        };
        Update: {
          cancel_at_period_end?: boolean;
          created_at?: string;
          current_period_end?: string | null;
          id?: string;
          status?: string;
          stripe_customer_id?: string;
          stripe_subscription_id?: string | null;
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [];
      };
      support_messages: {
        Row: {
          body: string;
          created_at: string;
          id: string;
          read_at: string | null;
          sender: string;
          user_id: string;
        };
        Insert: {
          body: string;
          created_at?: string;
          id?: string;
          read_at?: string | null;
          sender: string;
          user_id: string;
        };
        Update: {
          body?: string;
          created_at?: string;
          id?: string;
          read_at?: string | null;
          sender?: string;
          user_id?: string;
        };
        Relationships: [];
      };
      studio_rate_tiers: {
        Row: {
          created_at: string;
          id: string;
          max_attendance: number | null;
          min_attendance: number;
          rate: number;
          studio_id: string;
          user_id: string;
        };
        Insert: {
          created_at?: string;
          id?: string;
          max_attendance?: number | null;
          min_attendance: number;
          rate: number;
          studio_id: string;
          user_id: string;
        };
        Update: {
          created_at?: string;
          id?: string;
          max_attendance?: number | null;
          min_attendance?: number;
          rate?: number;
          studio_id?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'studio_rate_tiers_studio_id_fkey';
            columns: ['studio_id'];
            isOneToOne: false;
            referencedRelation: 'studios';
            referencedColumns: ['id'];
          },
        ];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};

type DatabaseWithoutInternals = Omit<Database, '__InternalSupabase'>;

type DefaultSchema = DatabaseWithoutInternals[Extract<
  keyof Database,
  'public'
>];

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema['Tables'] & DefaultSchema['Views'])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Views'])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Views'])[TableName] extends {
      Row: infer R;
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema['Tables'] &
        DefaultSchema['Views'])
    ? (DefaultSchema['Tables'] &
        DefaultSchema['Views'])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R;
      }
      ? R
      : never
    : never;

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    keyof DefaultSchema['Tables'] | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables']
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'][TableName] extends {
      Insert: infer I;
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema['Tables']
    ? DefaultSchema['Tables'][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I;
      }
      ? I
      : never
    : never;

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    keyof DefaultSchema['Tables'] | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables']
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'][TableName] extends {
      Update: infer U;
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema['Tables']
    ? DefaultSchema['Tables'][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U;
      }
      ? U
      : never
    : never;

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    keyof DefaultSchema['Enums'] | { schema: keyof DatabaseWithoutInternals },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions['schema']]['Enums']
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions['schema']]['Enums'][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema['Enums']
    ? DefaultSchema['Enums'][DefaultSchemaEnumNameOrOptions]
    : never;

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema['CompositeTypes']
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends (PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions['schema']]['CompositeTypes']
    : never) = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions['schema']]['CompositeTypes'][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema['CompositeTypes']
    ? DefaultSchema['CompositeTypes'][PublicCompositeTypeNameOrOptions]
    : never;

export const Constants = {
  public: {
    Enums: {},
  },
} as const;
